config/routes.rb
Rails.application.routes.draw do
  root to: 'file_upload#upload_form'

  controller :file_upload do
    get :upload_form
    post :upload
    post :upload_file
  end

  resources :files, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :model

  default_scope -> { includes(:model, :manufacturer) }

  def display_description
    [manufacturer.name, model.name, year, ref_id].select(&:present?).join(' - ')
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  def to_s
    self.name
  end

  def search_name
    name
  end
end

app/models/model.rb
class Model < ApplicationRecord
  def to_s
    name
  end

  def search_name
    name
  end
end

app/models/upload_form.rb
# == Schema Information
#
# Table name: upload_forms
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  comment    :string(255)
#  boat_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
require 'zip'

class UploadForm < ApplicationRecord
  belongs_to :boat, optional: true

  has_many :files, class_name: 'UploadedFile', foreign_key: :form_id, dependent: :destroy

  validates :name, presence: true
  validates :comment, presence: true, if: -> { boat.blank? }

  after_commit :make_zip_file, on: :create

  def self.auto_remove_old_files
    UploadForm.where('created_at <= ?', 3.weeks.ago).find_each do |form|
      File.delete(form.zip_path)
      form.destroy
    end
  end

  def self.send_mail
    UploadForm.where(sent_at: nil, zip_ready: true).each(&:send_mail)
  end

  def make_zip_file
    File.delete(zip_path) if File.exist?(zip_path)

    Zip::File.open(zip_path, Zip::File::CREATE) do |zipfile|
      files.each do |file|
        zipfile.add(file.file.url.split("/").last, file.file.path)
      end
    end

    update_columns(zip_ready: true)
  end

  def send_mail
    return unless zip_ready?
    return if sent_at?

    UserMailer.notify_new_file_upload(self).deliver_now
    update_columns(sent_at: Time.current)
  end

  def zip_path
    File.join("#{Rails.root}/public/uploads/uploaded_file/", "#{self.id}.zip")
  end

  def zip_url
    "https://uploads.boats.co.uk/uploads/uploaded_file/#{self.id}.zip"
  end
end

app/models/uploaded_file.rb
# == Schema Information
#
# Table name: uploaded_files
#
#  id         :integer          not null, primary key
#  file       :string(255)
#  form_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UploadedFile < ApplicationRecord
  mount_uploader :file, UploadFileUploader

  def self.remove_unattached_file
    UploadedFile.where(form_id: nil).destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :set_raven_context

  # def set_raven_context
  #   return if Rails.env.development? || Rails.env.test?

  #   Raven.user_context(id: session[:current_user_id])
  #   Raven.extra_context(params: params.to_unsafe_h, order_id: @order&.id, url: request.url)
  # end
end

app/controllers/file_upload_controller.rb
class FileUploadController < ApplicationController
  def upload_form
    @form = UploadForm.new
  end

  def upload
    files = params.dig(:upload_form, :files)
    @form = UploadForm.new(params.require(:upload_form).permit(:name, :boat_id, :comment))
    
    if files.present? && @form.save
      files.each do |file|
        UploadedFile.create(file: file, form_id: @form.id)
      end

      render json: @form, status: :ok
    else
      render json: { error: true }, status: :ok
    end
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def show
    file = UploadedFile.find(params[:id])
    send_file file.file.path, filename: file.file.name, disposition: 'attachment'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/file_upload/upload_form.haml
.container.form-wrapper
  .card
    = image_tag 'Boats-co-uk-since1969Final.png', class: 'logo'

    = simple_form_for UploadForm.new, url: upload_path, method: :post, html: { multipart: true } do |f|
      = f.input :name, label: false, input_html: { placeholder: 'Name' }
      = f.input :files, label: false, as: :file, input_html: { multiple: true }
      = f.input :boat_id, label: false, collection: Boat.where(state: :completed, is_live: true).sort_by(&:display_description), value_method: :id, label_method: :display_description, include_blank: 'Select Boat'
      = f.input :comment, label: false, as: :text, input_html: { rows: 4, placeholder: 'Comment' }

      .actions
        = f.submit 'Upload', class: 'btn btn-primary', data: { disable_with: 'Uploading' }

      #progress-bar
        .loading-bar
      #suggess-message
        %p File has been successfully uploaded

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no" }
    %title File Upload
    = csrf_meta_tags
    = csp_meta_tag
    %link{ rel: 'preconnect', href: "https://fonts.gstatic.com" }
    %link{ href: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap", rel: "stylesheet" }
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield